name: Cloud Functions

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

concurrency: ${{ github.ref }}

env:
  ENV_FILE: env.yaml
  GCP_SA: etl-95@byu-pathway-power-bi-report.iam.gserviceaccount.com

  FUNCTION_NAME: byu-pathway-matomo-${{ github.ref_name }}
  PUBLIC_URL: https://us-central1-charge-bee.cloudfunctions.net/byu-pathway-matomo-${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - uses: snok/install-poetry@v1

      - run: poetry export --without-hashes -o requirements.txt

      - run: |
          echo "MATOMO_TOKEN: ${{ secrets.MATOMO_TOKEN }}" >> ${{ env.ENV_FILE }}

          echo "GCP_SA: ${{ env.GCP_SA }}" >> ${{ env.ENV_FILE }}
          echo "PUBLIC_URL: ${{ env.PUBLIC_URL }}" >> ${{ env.ENV_FILE }}

      - run: >-
          gcloud functions deploy ${{ needs.set-env.outputs.fn-name }}
          --entry-point=main
          --region=us-central1
          --timeout=530
          --memory=256MB
          --runtime=python39
          --trigger-http
          --no-user-output-enabled
          --service-account=${{ env.GCP_SA }}
          --env-vars-file=${{ env.ENV_FILE }}
